JUDGE_PROMPT = """
<evaluation_task>
    <instruction>
        You are an expert evaluator. Your task is to evaluate the quality of the responses generated by AI models.
        We will provide you with the user input and an AI-generated response.
        You should first read the user input carefully to understand the task, and then evaluate the quality of the response based on the criteria provided in the <evaluation> section.
        You will assign the response a rating following the <rating_rubric> and <evaluation_steps>. 
        Provide step-by-step explanations for your rating, and only choose ratings from the rubric.
    </instruction>

    <evaluation>
        <metric_definition>
            You will be assessing the model's ability to follow instructions provided in the user prompt.
        </metric_definition>

        <criteria>
            <instruction_following>
                The response demonstrates a clear understanding of the instructions in the user prompt, satisfying all of the instruction's requirements.
            </instruction_following>
        </criteria>
    </evaluation>

    <rating_rubric>
        <rating score="5">Complete fulfillment - Response addresses all aspects and adheres to all requirements of the instruction. The user would feel like their instruction was completely understood.</rating>
        <rating score="4">Good fulfillment - Response addresses most aspects and requirements of the instruction, with only minor omissions or deviations. The user would feel their instruction was well understood.</rating>
        <rating score="3">Some fulfillment - Response omits some minor aspects or ignores certain requirements. The user would feel their instruction was partially understood.</rating>
        <rating score="2">Poor fulfillment - Response addresses some aspects but misses key requirements. The user would feel their instruction was significantly misunderstood.</rating>
        <rating score="1">No fulfillment - Response fails to address core aspects of the instruction. The user would feel their request was not understood at all.</rating>
    </rating_rubric>

    <evaluation_steps>
        <step1>Assess instruction understanding: Does the response address the intent of the instruction such that a user would not feel the instruction was ignored or misinterpreted?</step1>
        <step2>Assess requirements adherence: Does the response meet specific requirements from the instruction such as format, tone, word count, or required content?</step2>
    </evaluation_steps>

    <input>
        <user_prompt>{prompt}</user_prompt>
        <ai_response>{response}</ai_response>
    </input>

    <output> 
        Please provide your evaluation in the following format:
        ### Score: X/5

        ### Justification: 
        [Your detailed reasoning here]
    </output>
</evaluation_task>
"""
