apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: devpost-ai-app
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/vpc-access-connector: "mongodb-connector"
        run.googleapis.com/vpc-access-egress: "all-traffic"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/devpost-ai-in-action/devpost-ai-app:1751596867
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "devpost-ai-in-action"
        - name: DB_NAME
          value: "gitlab"
        - name: COLLECTION_NAME
          value: "incidents"
        - name: GITLAB_URL
          value: "https://gitlab.com"
        - name: GITLAB_PROJECT_URL
          value: "gitlab-com/gl-infra/production"
        - name: INCIDENTS_PATH
          value: "data/incidents.pkl"
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: atlas-uri
              key: latest
        - name: HUGGING_FACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: huggingface-api-token
              key: latest              
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-key
              key: latest          
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /_stcore/health
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 40
          timeoutSeconds: 20
          failureThreshold: 20